In [4]:
import pandas as pd

# Create the data dictionary
data = {
    'Student_ID': [1001, 1002, 1003, 1004, 1005],
    'Name': ['Arun', 'Priya', 'John', 'Meena', 'Ravi'],
    'Dept': ['CSE', 'ECE', 'MECH', 'CSE', 'Civil'],
    'Attendance': [95, 80, 75, 98, 88],
    'Marks': [85, 72, 68, 91, 77],
    'Placement': ['Yes', 'No', 'No', 'Yes', 'Yes']
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

# To view the data types of each column
# print(df.dtypes)

   Student_ID   Name   Dept  Attendance  Marks Placement
0        1001   Arun    CSE          95     85       Yes
1        1002  Priya    ECE          80     72        No
2        1003   John   MECH          75     68        No
3        1004  Meena    CSE          98     91       Yes
4        1005   Ravi  Civil          88     77       Yes

In [5]:
df.head()

   Student_ID   Name   Dept  Attendance  Marks Placement
0        1001   Arun    CSE          95     85       Yes
1        1002  Priya    ECE          80     72        No
2        1003   John   MECH          75     68        No
3        1004  Meena    CSE          98     91       Yes
4        1005   Ravi  Civil          88     77       Yes

In [7]:
df.tail()

   Student_ID   Name   Dept  Attendance  Marks Placement
0        1001   Arun    CSE          95     85       Yes
1        1002  Priya    ECE          80     72        No
2        1003   John   MECH          75     68        No
3        1004  Meena    CSE          98     91       Yes
4        1005   Ravi  Civil          88     77       Yes

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  5 non-null      int64
 1   Name        5 non-null      object
 2   Dept        5 non-null      object
 3   Attendance  5 non-null      int64
 4   Marks       5 non-null      int64
 5   Placement   5 non-null      object
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes

In [9]:
df.describe()

        Student_ID  Attendance      Marks
count     5.000000    5.000000   5.000000
mean   1003.000000   87.200000  78.600000
std       1.581139    9.731393   9.396808
min    1001.000000   75.000000  68.000000
25%    1002.000000   80.000000  72.000000
50%    1003.000000   88.000000  77.000000
75%    1004.000000   95.000000  85.000000
max    1005.000000   98.000000  91.000000

In [10]:
df.shape

(5, 6)

In [11]:
df.columns

Index(['Student_ID', 'Name', 'Dept', 'Attendance', 'Marks', 'Placement'], dtype='object')

In [12]:
print(df.dtypes)

Student_ID     int64
Name          object
Dept          object
Attendance     int64
Marks          int64
Placement     object
dtype: object

In [16]:
print(df["Name"])

0     Arun
1    Priya
2     John
3    Meena
4     Ravi
Name: Name, dtype: object

In [18]:
print(df.loc[0])

Student_ID    1001
Name          Arun
Dept           CSE
Attendance      95
Marks           85
Placement      Yes
Name: 0, dtype: object

In [19]:
print(df.iloc[0])

Student_ID    1001
Name          Arun
Dept           CSE
Attendance      95
Marks           85
Placement      Yes
Name: 0, dtype: object

In [20]:
print(df[df["Marks"]>75])

   Student_ID   Name   Dept  Attendance  Marks Placement
0        1001   Arun    CSE          95     85       Yes
3        1004  Meena    CSE          98     91       Yes
4        1005   Ravi  Civil          88     77       Yes

In [21]:
df.sort_values(by="Marks", ascending=False)

   Student_ID   Name   Dept  Attendance  Marks Placement
3        1004  Meena    CSE          98     91       Yes
0        1001   Arun    CSE          95     85       Yes
4        1005   Ravi  Civil          88     77       Yes
1        1002  Priya    ECE          80     72        No
2        1003   John   MECH          75     68        No

In [22]:
df.groupby("Dept")["Marks"].mean()

Dept
CSE      88.0
Civil    77.0
ECE      72.0
MECH     68.0
Name: Marks, dtype: float64

In [23]:
df["Marks"].mean()

np.float64(78.6)

In [24]:

import pandas as pd

# 1. Initialize the Student Database
columns = ['Student_ID', 'Name', 'Dept', 'Attendance', 'Marks', 'Placement']
student_df = pd.DataFrame(columns=columns)

def add_student(df):
    """Adds a new student record with strict placement validation."""
    print("\n--- Add New Student ---")
    s_id = input("Enter Student ID: ")
    name = input("Enter Name: ")
    dept = input("Enter Department: ")
    try:
        att = float(input("Enter Attendance (%): "))
        marks = float(input("Enter Marks: "))
    except ValueError:
        print("Error: Attendance and Marks must be numbers.")
        return df
    
    # Validating Placement input
    placement = ""
    while placement not in ['yes', 'no']:
        placement = input("Placement Status (yes/no): ").lower().strip()
        if placement not in ['yes', 'no']:
            print("Invalid input. Please enter 'yes' or 'no'.")

    new_data = pd.DataFrame([[s_id, name, dept, att, marks, placement]], columns=columns)
    df = pd.concat([df, new_data], ignore_index=True)
    print(f"Record for {name} added successfully!")
    return df

def find_average(df):
    """Calculates the average marks of all students."""
    if df.empty:
        print("No records found to calculate average.")
    else:
        avg = df['Marks'].mean()
        print(f"\nAverage Marks across all students: {avg:.2f}")

def search_student(df):
    """Searches for a student by ID or Name."""
    query = input("\nEnter Student ID or Name to search: ")
    result = df[(df['Student_ID'] == query) | (df['Name'].str.contains(query, case=False, na=False))]
    if result.empty:
        print("No student found with those details.")
    else:
        print("\n--- Search Results ---")
        print(result.to_string(index=False))

def performance_analysis(df):
    """Provides a brief analysis based on marks and attendance."""
    if df.empty:
        print("No records available for analysis.")
        return
    
    print("\n--- Student Performance Analysis ---")
    highest = df.loc[df['Marks'].idxmax()]
    print(f"Topper: {highest['Name']} with {highest['Marks']} Marks.")
    
    # Analysis based on attendance thresholds
    low_attendance = df[df['Attendance'] < 75]
    if not low_attendance.empty:
        print(f"Warning: {len(low_attendance)} students have attendance below 75%.")
    
    # Placement vs Marks
    placed_count = len(df[df['Placement'] == 'yes'])
    print(f"Total Placed: {placed_count} / {len(df)}")

# --- Main Menu Loop ---
while True:
    print("\n--- Student Management System ---")
    print("1. Add Student")
    print("2. View All Students")
    print("3. Find Average Marks")
    print("4. Search Student")
    print("5. Performance Analysis")
    print("6. Exit")
    
    choice = input("Select an option (1-6): ")
    
    if choice == '1':
        student_df = add_student(student_df)
    elif choice == '2':
        print(student_df.to_string(index=False)) if not student_df.empty else print("Empty Database.")
    elif choice == '3':
        find_average(student_df)
    elif choice == '4':
        search_student(student_df)
    elif choice == '5':
        performance_analysis(student_df)
    elif choice == '6':
        break
    else:
        print("Invalid choice.")

--- Student Management System ---
1. Add Student
2. View All Students
3. Find Average Marks
4. Search Student
5. Performance Analysis
6. Exit

Select an option (1-6):  1

--- Add New Student ---

Enter Student ID:  123
Enter Name:  anju
Enter Department:  CSE
Enter Attendance (%):  23
Enter Marks:  75
Placement Status (yes/no):  no

Record for anju added successfully!

--- Student Management System ---
1. Add Student
2. View All Students
3. Find Average Marks
4. Search Student
5. Performance Analysis
6. Exit

C:\Users\anju\AppData\Local\Temp\ipykernel_80104\2552400401.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_data], ignore_index=True)

Select an option (1-6):  4

Enter Student ID or Name to search:  123

--- Search Results ---
Student_ID Name Dept  Attendance  Marks Placement
       123 anju  CSE        23.0   75.0        no

--- Student Management System ---
1. Add Student
2. View All Students
3. Find Average Marks
4. Search Student
5. Performance Analysis
6. Exit

Select an option (1-6):  5

--- Student Performance Analysis ---
Topper: anju with 75.0 Marks.
Warning: 1 students have attendance below 75%.
Total Placed: 0 / 1

--- Student Management System ---
1. Add Student
2. View All Students
3. Find Average Marks
4. Search Student
5. Performance Analysis
6. Exit

Select an option (1-6):  6